serviceMonitor:
  enabled: true
  # serviceMonitor.labels -- labels to set on the vault serviceMonitor
  labels: {}
  # scrapeTimeout  -- scrapeTimeout of the serviceMonitor
  scrapeTimeout: 30s

  scrapeInterval: 30s

  # -- Specify the Kubernetes namespace where Prometheus expects to find
  # service monitors configured.
  # namespace: ""

  # -- Relabeling configs for the ServiceMonitor
  relabelings: []
  # -- Metrics relabeling configs for the ServiceMonitor
  metricRelabelings: ~

prometheus:
  # -- Create prometheus-operator resources
  enabled: true
  rule:
    # -- Optional Namespace for PrometheusRule resource
    namespace: ""
    # -- Additional Labels for PrometheusRule resource
    additionalLabels: {}
    alerts:
      volumeActualSpaceUsedWarning:
        enabled: true
        severity: warning
        threshold: 90
      volumeStatusCritical:
        enabled: true
        severity: critical
      volumeStatusWarning:
        enabled: true
        severity: warning
      nodeStorageWarning:
        enabled: true
        severity: warning
        threshold: 70
      diskStorageWarning:
        enabled: true
        severity: warning
        threshold: 70
      nodeDown:
        enabled: true
        severity: critical
      instanceManagerCPUUsageWarning:
        enabled: true
        severity: warning
      nodeCPUUsageWarning:
        enabled: true
        severity: warning
    additionalAlerts: []
    # - alert: CertManagerCertificateReadyStatus
    #   annotations:
    #     description: 'Failed node exist in cluster'
    #     summary: Number Of Failed Nodes above zero
    #   expr: (avg(longhorn_node_count_total) OR on() vector(0)) - (count(longhorn_node_status{condition="ready"}==1) OR on() vector(0)) == 1
    #   labels:
    #     severity: critical

grafana:
  # -- Enable deploying longhorn dashboard to Grafana
  enabled: false
  # -- Add `grafana_dashboard: "1"` default label
  defaultLabel: true
  # -- Extra labels for dashboard ConfigMap
  extraLabels: {}
  # -- Extra annotations for dashboard ConfigMap
  extraAnnotations: {}
  # -- Optional Namespace for Grafana dashboard
  namespace: ""
