{{- if $.Values.serviceMonitor.enabled ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" )  }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-prometheus-service-monitor
  namespace: {{ $.Values.serviceMonitor.namespace | default $.Release.Namespace }}
  labels:
    {{- include "redis-monitoring.labels" . | nindent 4 }}
    {{- if $.Values.serviceMonitor.labels }}
    {{- toYaml $.Values.serviceMonitor.labels | nindent 4}}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: redis-manager
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  endpoints:
    - port: manager
      scrapeTimeout: {{ $.Values.serviceMonitor.scrapeTimeout }}
      interval: {{ $.Values.serviceMonitor.scrapeInterval }}
{{- end }}
