apiVersion: v2
name: cert-manager-issuers
description: Configure cert-manager Issuers and ClusterIssuers via Helm
type: application
version: 0.1.0
# matches apiVersion: cert-manager.io/v1
appVersion: "1"
keywords:
  - cert-manager
  - tls
icon: https://raw.githubusercontent.com/SomeBlackMagic/helm-charts/master/charts/cert-manager-issuers/logo.png
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x

  - name: someblackmagic-common
    repository: https://someblackmagic.github.io/helm-charts
    tags:
      - someblackmagic-common
    version: 0.x.x
