{{- if and $.Values.prometheus.enabled ( $.Capabilities.APIVersions.Has "monitoring.coreos.com/v1" )  }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "kube-monitoring.fullname" . }}
  {{- if $.Values.prometheus.rule.namespace }}
  namespace: {{ $.Values.prometheus.rule.namespace }}
  {{- end }}
  labels:
    {{- include "kube-monitoring.labels" . | nindent 4 }}
    {{- if $.Values.prometheus.rule.additionalLabels }}
    {{- toYaml $.Values.prometheus.rule.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  groups:
  - name: kube-monitoring
    rules:
    {{- if $.Values.prometheus.rule.alerts.horizontalPodAutoscalerIsNotActive.enabled }}
    - alert: KubeHorizontalPodAutoscalerIsNotActive
      annotations:
        description: {{`HorizontalPodAutoscaler {{$labels.horizontalpodautoscaler}} in namespace {{$labels.namespace}}
          is not work or unknown status more than 5 minutes.`}}
        summary: The HorizontalPodAutoscaler not work not active.
      expr: (kube_horizontalpodautoscaler_status_condition{condition="ScalingActive", status="false"} == 1 or kube_horizontalpodautoscaler_status_condition{condition="ScalingActive", status="unknown"}  == 1)
      for: 5m
      labels:
        severity: "{{ $.Values.prometheus.rule.alerts.horizontalPodAutoscalerIsNotActive.severity }}"
    {{- end }}

    {{- if $.Values.prometheus.rule.alerts.horizontalPodAutoscalerIsNotAbleToScale.enabled }}
    - alert: KubeHorizontalPodAutoscalerIsNotAbleToScale
      annotations:
        description: {{`HorizontalPodAutoscaler {{$labels.horizontalpodautoscaler}} in namespace {{$labels.namespace}}
          is not able to scale or unknown status more than 5 minutes.`}}
        summary: The HorizontalPodAutoscaler Is Not Able To Scale.
      expr: (kube_horizontalpodautoscaler_status_condition{condition="AbleToScale", status="false"} == 1 or kube_horizontalpodautoscaler_status_condition{condition="AbleToScale", status="unknown"}  == 1)
      for: 5m
      labels:
        severity: "{{ $.Values.prometheus.rule.alerts.horizontalPodAutoscalerIsNotAbleToScale.severity }}"
    {{- end }}

    {{- if $.Values.prometheus.rule.alerts.containerIsOOMKilled.enabled }}
    #https://github.com/PostHog/charts-clickhouse/blob/26d2568433b8fc772d400656120b3d130b787b4f/charts/posthog/values.yaml#L2463
    - alert: KubeContainerIsOOMKilled
      annotations:
        summary: {{`Kubernetes container oom killer (instance {{ $labels.instance }})`}}
        description: {{`Container {{ $labels.container }} in pod {{ $labels.namespace }}/{{ $labels.pod }} has been OOMKilled {{ $value }} times in the last 10 minutes.`}}
      expr: (kube_pod_container_status_restarts_total - kube_pod_container_status_restarts_total offset 10m >= 1) and ignoring (reason) min_over_time(kube_pod_container_status_last_terminated_reason{reason="OOMKilled"}[10m]) == 1
      for: 10m
      labels:
        severity: "{{ $.Values.prometheus.rule.alerts.containerIsOOMKilled.severity }}"
    {{- end }}

    {{- if $.Values.prometheus.rule.alerts.failedEvictedPods.enabled }}
    #https://stackoverflow.com/a/69340335
    - alert: FailedEvictedPods
      annotations:
        summary: "{{`Failed Evicted pod: {{ $labels.pod }}`}}"
        description: "{{`Pod {{ $labels.namespace }}/{{ $labels.pod }} has been Evicted. Please check reason and remove evicted pod`}}"
      expr: sum by(namespace, pod) (kube_pod_status_phase{phase="Failed"} > 0 and on(namespace, pod) kube_pod_status_reason{reason="Evicted"} > 0) > 0
      for: 10m
      labels:
        severity: "{{ $.Values.prometheus.rule.alerts.failedEvictedPods.severity }}"
    {{- end }}

    {{- if $.Values.prometheus.rule.alerts.tooManyEvictedPods.enabled }}
    #https://stackoverflow.com/a/69340335
    - alert: TooManyEvictedPodsOnNamespace
      annotations:
        summary: "{{`Too many Failed Evicted Pods in {{ $labels.namespace }}`}}"
        description: "{{`Too many Failed Evicted Pods: {{ $value }} on namespace {{ $labels.namespace }}`}}"
      expr: sum by(namespace) (kube_pod_status_reason{reason="Evicted"}) >= {{ $.Values.prometheus.rule.alerts.tooManyEvictedPods.threshold }}
      labels:
        severity: "{{ $.Values.prometheus.rule.alerts.tooManyEvictedPods.severity }}"
    {{- end }}



    {{- with $.Values.prometheus.rule.additionalAlerts }}
    {{ . | nindent 4 }}
    {{- end }}
{{- end }}
