apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-ui
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  replicas: {{ $.Values.ui.replicaCount }}
  strategy: {{- toYaml $.Values.ui.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      app.kubernetes.io/chart-name: {{ $.Chart.Name }}
      app.kubernetes.io/release-name: {{ $.Release.Name }}
      app.kubernetes.io/application-type: ui
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ $.Release.Name }} # duplicate release name only for work helm-assistant
        app.kubernetes.io/chart-name: {{ $.Chart.Name }}
        app.kubernetes.io/release-name: {{ $.Release.Name }}
        app.kubernetes.io/application-type: ui
        app.metadata.io/version: {{ $.Chart.AppVersion | default $.Values.ui.image.tag | trunc 63 }}
        checksum/config: {{ include (print $.Template.BasePath "/ui/config-map.yaml") . | sha256sum | trunc 63 }}
        {{- if $.Values.ui.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" $.Values.ui.podLabels "context" $) | nindent 8 }}
        {{- end }}
      annotations:
        {{- if $.Values.ui.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" $.Values.ui.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: false
      {{- if $.Values.ui.podSecurityContext.enabled }}
      securityContext: {{- omit $.Values.ui.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if $.Values.ui.image.pullSecrets }}
      imagePullSecrets: {{ toYaml $.Values.ui.image.pullSecrets | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      containers:
        - name: allure
          {{- with $.Values.ui.image }}
          image: "{{- if .registry -}}{{ .registry }}/{{ .repository }}{{ else }}{{ .repository }}{{- end -}}:{{ .tag }}{{- if (.digest) -}} @{{.digest}} {{- end -}}"
          {{- end }}
          imagePullPolicy: {{ $.Values.ui.image.pullPolicy }}

          envFrom:
            {{- include "common.containerEnvVarsSecrets" (dict "value" $.Values.ui.extraEnvVarsSecrets "context" $) | nindent 12 }}
            - configMapRef:
                name: {{ $.Release.Name }}-ui-config-map


          env: {{- include "common.containerEnvVars" (dict "value" $.Values.ui.extraEnvVars "context" $) | nindent 12 }}

          {{- if $.Values.ui.resources.enabled }}
          resources: {{- omit $.Values.ui.resources "enabled" | toYaml | nindent 12 }}
          {{- end }}

          {{- if $.Values.ui.containerSecurityContext.enabled }}
          securityContext: {{- omit $.Values.ui.containerSecurityContext "enabled" "active" | toYaml | nindent 12 }}
          {{- end }}

          ports:
            - containerPort: {{ $.Values.ui.containerPorts.application }}
              name: application
              protocol: TCP

{{/*          volumeMounts:*/}}
{{/*            - name: reports-volume*/}}
{{/*              mountPath: /app/allure-docker-api/static/projects/default/reports*/}}
{{/*            - name: results-volume*/}}
{{/*              mountPath: /app/allure-docker-api/static/projects/default/results*/}}

          {{- if $.Values.ui.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" $.Values.ui.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}

          {{- if $.Values.ui.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              port: {{ $.Values.ui.containerPorts.application }}
              path: /
            initialDelaySeconds: {{ $.Values.ui.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ $.Values.ui.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ $.Values.ui.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ $.Values.ui.readinessProbe.failureThreshold }}
            successThreshold: {{ $.Values.ui.readinessProbe.successThreshold }}
          {{- end }}


      volumes:
{{/*        - name: results-volume*/}}
{{/*          emptyDir: { }*/}}
        {{- if $.Values.ui.extraVolumes }}
        {{- include "common.tplvalues.render" ( dict "value" $.Values.ui.extraVolumes "context" $) | nindent 8 }}
        {{- end }}

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/chart-name: {{ $.Chart.Name }}
                    app.kubernetes.io/release-name: {{ $.Release.Name }}
                    app.kubernetes.io/application-type: ui
                topologyKey: kubernetes.io/hostname
