apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-server-config-map
data:
  CHECK_RESULTS_EVERY_SECONDS: 'NONE'
  KEEP_HISTORY: "1"
  URL_PREFIX: "/allure-api"
  TLS: "1"
  SECURITY_ENABLED: "1"
  MAKE_VIEWER_ENDPOINTS_PUBLIC: "0"