apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-server-secrets
  labels:
    app.kubernetes.io/chart-name: {{ $.Chart.Name }}
    app.kubernetes.io/release-name: {{ $.Release.Name }}
    app.kubernetes.io/application-type: server
type: Opaque
data:
  {{- range $key, $val := $.Values.server.envSecrets }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}