replicaCount: 1

clusterDomain: "cluster.local"

image:
  repository: haproxy
  tag: 2.9

service:
  type: ClusterIP
  ports:
    - name: dashboard
      port: 8080
      targetPort: 8080
    - name: redis-write
      port: 6379
      targetPort: 6379
    - name: redis-read
      port: 6380
      targetPort: 6380

configmap:
  global:
    maxconn: 256
  defaults:
    timeoutConnect: "5000ms"
    timeoutClient: "50000ms"
    timeoutServer: "50000ms"
  frontendHttpEnabled: true
  backendStats:
    uri: "/"
    refresh: "1s"
    admin: "TRUE"

  frontend:
    redisReadPort: 6380
    redisWritePort: 6379

  backend:
    redisServerCount: 3
    balanceAlgorithm: "first"

  resolvers:
    holdOther: "10s"
    holdRefused: "10s"
    holdNx: "10s"
    holdTimeout: "10s"
    holdValid: "10s"
    holdObsolete: "10s"

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
              - haproxy
        topologyKey: "kubernetes.io/hostname"
redis:

  ## @param architecture Redis(TM) architecture. Allowed values: `standalone` or `replication`
  ##
  architecture: replication

  sentinel:
    enabled: true
