apiVersion: v2
name: ingress-nginx-monitoring
description: Monitor nginx ingress controller
type: application
version: 1.2.6
appVersion: 1.2.6
icon: https://raw.githubusercontent.com/SomeBlackMagic/helm-charts/master/charts/ingress-nginx-monitoring/nginx-prometheus-grafana.png
keywords:
  - http
  - nginx
  - monitoring
sources:
  - https://github.com/SomeBlackMagic/helm-charts
maintainers:
  - name: Andru Cherny
    url: https://github.com/wirwolf
