prometheus:
  # -- Create prometheus-operator resources
  enabled: true
  rule:
    # -- Optional Namespace for PrometheusRule resource
    namespace: ""
    # -- Additional Labels for PrometheusRule resource
    additionalLabels: {}

    ingressClass: ".*"

    alerts:
      configFailed:
        enabled: true
        severity: critical

      certificateExpiry:
        enabled: true
        severity: critical

      tooMany500s:
        enabled: true
        severity: error

      tooMany400s:
        enabled: true
        severity: warning

    additionalAlerts: []
    # - alert: CertManagerCertificateReadyStatus
    #   annotations:
    #     description: 'Certificate for "{{`{{ $labels.name }}`}}" is not ready.'
    #     summary: Certificate is not ready
    #   expr: certmanager_certificate_ready_status{condition="False"} == 1
    #   labels:
    #     severity: critical

grafana:
  # -- Enable deploying cert-manager dashboard to Grafana
  enabled: false
  # -- Add `grafana_dashboard: "1"` default label
  defaultLabel: true
  # -- Extra labels for dashboard ConfigMap
  extraLabels: {}
  # -- Extra annotations for dashboard ConfigMap
  extraAnnotations: {}
