{{- if and $.Values.prometheus.enabled ( $.Capabilities.APIVersions.Has "monitoring.coreos.com/v1" )  }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "longhorn-monitoring.fullname" . }}
  {{- if $.Values.prometheus.rule.namespace }}
  namespace: {{ $.Values.prometheus.rule.namespace }}
  {{- end }}
  labels:
    {{- include "longhorn-monitoring.labels" . | nindent 4 }}
    {{- if $.Values.prometheus.rule.additionalLabels }}
    {{- toYaml $.Values.prometheus.rule.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  groups:
  - name: longhorn
    rules:
    {{- if $.Values.prometheus.rule.alerts.volumeActualSpaceUsedWarning.enabled }}
    - alert: LonghornVolumeActualSpaceUsedWarning
      annotations:
        description: {{`The actual space used by Longhorn volume {{$labels.volume}} on {{$labels.node}} is at {{$value}}% capacity for
          more than 5 minutes.`}}
        summary: The actual used space of Longhorn volume is over 90% of the capacity.
      expr: (longhorn_volume_actual_size_bytes / longhorn_volume_capacity_bytes) * 100 > {{ $.Values.prometheus.rule.alerts.volumeActualSpaceUsedWarning.threshold }}
      for: 5m
      labels:
        issue: {{`The actual used space of Longhorn volume {{$labels.volume}} on {{$labels.node}} is high.`}}
        severity: "{{ $.Values.prometheus.rule.alerts.volumeActualSpaceUsedWarning.severity }}"
    {{- end }}

    {{- if $.Values.prometheus.rule.alerts.volumeStatusCritical.enabled }}
    - alert: LonghornVolumeStatusCritical
      annotations:
        description: {{`Longhorn volume {{$labels.volume}} on {{$labels.node}} is Fault for
          more than 2 minutes.`}}
        summary: {{`Longhorn volume {{$labels.volume}} is Fault`}}
      expr: longhorn_volume_robustness == 3
      for: 5m
      labels:
        issue: {{`Longhorn volume {{$labels.volume}} is Fault.`}}
        severity: "{{ $.Values.prometheus.rule.alerts.volumeStatusCritical.severity }}"
    {{- end }}

    {{- if $.Values.prometheus.rule.alerts.volumeStatusWarning.enabled }}
    - alert: LonghornVolumeStatusWarning
      annotations:
        description: {{`Longhorn volume {{$labels.volume}} on {{$labels.node}} is Degraded for
          more than 5 minutes.`}}
        summary: {{`Longhorn volume {{$labels.volume}} is Degraded`}}
      expr: longhorn_volume_robustness == 2
      for: 5m
      labels:
        issue: {{`Longhorn volume {{$labels.volume}} is Degraded.`}}
        severity: "{{ $.Values.prometheus.rule.alerts.volumeStatusWarning.severity }}"
    {{- end }}

    {{- if $.Values.prometheus.rule.alerts.nodeStorageWarning.enabled }}
    - alert: LonghornNodeStorageWarning
      annotations:
        description: {{`The used storage of node {{$labels.node}} is at {{$value}}% capacity for
          more than 5 minutes.`}}
        summary:  The used storage of node is over {{ $.Values.prometheus.rule.alerts.nodeStorageWarning.threshold }}% of the capacity.
      expr: (longhorn_node_storage_usage_bytes / longhorn_node_storage_capacity_bytes) * 100 > {{ $.Values.prometheus.rule.alerts.nodeStorageWarning.threshold }}
      for: 5m
      labels:
        issue: {{`The used storage of node {{$labels.node}} is high.`}}
        severity: "{{ $.Values.prometheus.rule.alerts.nodeStorageWarning.severity }}"
    {{- end }}

    {{- if $.Values.prometheus.rule.alerts.diskStorageWarning.enabled }}
    - alert: LonghornDiskStorageWarning
      annotations:
        description: {{`The used storage of disk {{$labels.disk}} on node {{$labels.node}} is at {{$value}}% capacity for
          more than 5 minutes.`}}
        summary:  The used storage of disk is over {{ $.Values.prometheus.rule.alerts.diskStorageWarning.threshold }}% of the capacity.
      expr: (longhorn_disk_usage_bytes / longhorn_disk_capacity_bytes) * 100 > {{ $.Values.prometheus.rule.alerts.diskStorageWarning.threshold }}
      for: 5m
      labels:
        issue: {{`The used storage of disk {{$labels.disk}} on node {{$labels.node}} is high.`}}
        severity: "{{ $.Values.prometheus.rule.alerts.diskStorageWarning.severity }}"
    {{- end }}

    {{- if $.Values.prometheus.rule.alerts.nodeDown.enabled }}
    - alert: LonghornNodeDown
      annotations:
        description: {{`There are {{$value}} Longhorn nodes which have been offline for more than 5 minutes.`}}
        summary: Longhorn nodes is offline
      expr: (avg(longhorn_node_count_total) or on() vector(0)) - (count(longhorn_node_status{condition="ready"} == 1) or on() vector(0)) > 0
      for: 5m
      labels:
        issue: {{`There are {{$value}} Longhorn nodes are offline`}}
        severity: "{{ $.Values.prometheus.rule.alerts.nodeDown.severity }}"
    {{- end }}

    {{- if $.Values.prometheus.rule.alerts.instanceManagerCPUUsageWarning.enabled }}
    - alert: LonghornInstanceManagerCPUUsageWarning
      annotations:
        description: {{`Longhorn instance manager {{$labels.instance_manager}} on {{$labels.node}} has CPU Usage / CPU request is {{$value}}% for
          more than 5 minutes.`}}
        summary: {{`Longhorn instance manager {{$labels.instance_manager}} on {{$labels.node}} has CPU Usage / CPU request is over 300%.`}}
      expr: (longhorn_instance_manager_cpu_usage_millicpu/longhorn_instance_manager_cpu_requests_millicpu) * 100 > 300
      for: 5m
      labels:
        issue: {{`Longhorn instance manager {{$labels.instance_manager}} on {{$labels.node}} consumes 3 times the CPU request.`}}
        severity: "{{ $.Values.prometheus.rule.alerts.instanceManagerCPUUsageWarning.severity }}"
    {{- end }}

    {{- if $.Values.prometheus.rule.alerts.nodeCPUUsageWarning.enabled }}
    - alert: LonghornNodeCPUUsageWarning
      annotations:
        description: {{`Longhorn node {{$labels.node}} has CPU Usage / CPU capacity is {{$value}}% for
          more than 5 minutes.`}}
        summary: {{`Longhorn node {{$labels.node}} experiences high CPU pressure for more than 5m.`}}
      expr: (longhorn_node_cpu_usage_millicpu / longhorn_node_cpu_capacity_millicpu) * 100 > 90
      for: 5m
      labels:
        issue: {{`Longhorn node {{$labels.node}} experiences high CPU pressure.`}}
        severity: "{{ $.Values.prometheus.rule.alerts.nodeCPUUsageWarning.severity }}"
    {{- end }}

    {{- with $.Values.prometheus.rule.additionalAlerts }}
    {{ . | nindent 4 }}
    {{- end }}
{{- end }}
