apiVersion: v1
kind: Service
metadata:
  name: {{ include "haproxy.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "haproxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
  {{- end }}
  selector:
    app: {{ include "haproxy.name" . }}
