{{- if and $.Values.prometheus.enabled ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $.Release.Name }}-fluent-bit
  {{- if $.Values.prometheus.rule.namespace }}
  namespace: {{ $.Values.prometheus.rule.namespace }}
  {{- end }}
  labels:
    {{ include "banzaicloud-logging-operator-monitoring.labels" . | nindent 4 }}
    {{- if $.Values.prometheus.rule.additionalLabels }}
    {{ toYaml $.Values.prometheus.rule.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  groups:
  - name: logging-operator-fluent-bit
    rules:

    {{- if $.Values.prometheus.rule.alerts.fluentBit.serviceDown.enabled }}
    - alert: FluentBitDown
      expr: absent(up{container="fluent-bit",namespace="{{ $.Release.Namespace }}"}== 1)
      for: {{ $.Values.prometheus.rule.alerts.fluentBit.serviceDown.for }}
      labels:
        severity: "{{ $.Values.prometheus.rule.alerts.fluentBit.serviceDown.severity }}"
      annotations:
        summary: "Fluent Bit Down"
        description: {{`"Fluent Bit on {{ $labels.instance }} is down. No logs will be collected."`}}
    {{- end }}

    {{- if $.Values.prometheus.rule.alerts.fluentBit.noOutputBytesProcessed.enabled }}
    - alert: FluentBitNoOutputBytesProcessed
      expr: rate(fluentbit_output_proc_bytes_total[{{ $.Values.prometheus.rule.alerts.fluentBit.noOutputBytesProcessed.rateTime }}]) == 0
      for: {{ $.Values.prometheus.rule.alerts.fluentBit.noOutputBytesProcessed.for }}
      labels:
        severity: "{{ $.Values.prometheus.rule.alerts.fluentBit.noOutputBytesProcessed.severity }}"
      annotations:
        summary: "Fluent Bit no output bytes processed"
        description: {{`"Output plugin {{ $labels.name }} on Pod {{ $labels.namespace }}/{{ $labels.pod }} has not processed any bytes.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"`}}
    {{- end }}

    {{- if $.Values.prometheus.rule.alerts.fluentBit.noInputBytesProcessed.enabled }}
    - alert: FluentBitNoInputBytesProcessed
      expr: sum by (pod) (increase(fluentbit_input_bytes_total{container=~"fluent-bit.*"}[{{ $.Values.prometheus.rule.alerts.fluentBit.noInputBytesProcessed.increaseTime }}])) == 0
      for: {{ $.Values.prometheus.rule.alerts.fluentBit.noInputBytesProcessed.for }}
      labels:
        severity: "{{ $.Values.prometheus.rule.alerts.fluentBit.noInputBytesProcessed.severity }}"
      annotations:
        summary: "Fluent Bit input plugins have not processed any data"
        description: {{`"The input plugins of Fluent Bit pod {{ $labels.pod }} have not collected any logs.\n  LABELS: {{ $labels }}"`}}
    {{- end }}


    {{- with $.Values.prometheus.rule.additionalAlerts }}
    {{ . | nindent 4 }}
    {{- end }}
{{- end }}
