{{- if and $.Values.prometheus.enabled ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $.Release.Name }}-fluentd
  {{- if .Values.prometheus.rule.namespace }}
  namespace: {{ .Values.prometheus.rule.namespace }}
  {{- end }}
  labels:
    {{ include "banzaicloud-logging-operator-monitoring.labels" . | nindent 4 }}
    {{- if .Values.prometheus.rule.additionalLabels }}
    {{ toYaml .Values.prometheus.rule.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  groups:
  - name: logging-operator-fluentd
    rules:

    {{- if .Values.prometheus.rule.alerts.fluentd.serviceDown.enabled }}
    - alert: FluentdDown
      expr: kube_statefulset_status_replicas{statefulset=~".*fluentd.*",namespace="{{ $.Release.Namespace }}"} == 0
      for: {{ $.Values.prometheus.rule.alerts.fluentd.serviceDown.for }}
      labels:
        context: fluentd
        severity: "{{ $.Values.prometheus.rule.alerts.fluentd.serviceDown.severity }}"
      annotations:
        summary: "Fluentd Down"
        description: {{`"{{ $labels.statefulset }} on {{ $labels.instance }} is down"`}}
    {{- end }}


    {{- if .Values.prometheus.rule.alerts.fluentd.outputBufferWarning.enabled }}
    - alert: FluentdOutputBufferWarning
      expr: max_over_time(fluentd_output_status_buffer_queue_length[{{ $.Values.prometheus.rule.alerts.fluentd.outputBufferWarning.lookbackTime }}]) > {{ $.Values.prometheus.rule.alerts.fluentd.outputBufferWarning.threshold }}
      for: {{ $.Values.prometheus.rule.alerts.fluentd.outputBufferWarning.for }}
      labels:
        severity: "{{ $.Values.prometheus.rule.alerts.fluentd.outputBufferWarning.severity }}"
      annotations:
        summary: {{`"Fluentd output buffer growing (instance {{ $labels.instance }})"`}}
        description: {{`"Fluentd is not forwarding all logs\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"`}}
    {{- end }}

    {{- if .Values.prometheus.rule.alerts.fluentd.outputRetryWarning.enabled }}
    - alert: FluentdOutputRetryWarning
      expr: rate(fluentd_output_status_retry_count{plugin_id!~"{{ $.Values.prometheus.rule.alerts.fluentd.excludePluginIdRegex }}"}[{{ $.Values.prometheus.rule.alerts.fluentd.outputRetryWarning.rateTime }}]) > {{ $.Values.prometheus.rule.alerts.fluentd.outputRetryWarning.threshold }}
      for: {{ $.Values.prometheus.rule.alerts.fluentd.outputRetryWarning.for }}
      labels:
        severity: "{{ $.Values.prometheus.rule.alerts.fluentd.outputRetryWarning.severity }}"
      annotations:
        summary: {{`"Fluentd output retry counter is high (instance {{ $labels.instance }})"`}}
        description: {{`"Fluentd is not forwarding all logs\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"`}}
    {{- end }}

    {{- if .Values.prometheus.rule.alerts.fluentd.outputBufferQueueLength.enabled }}
    - alert: FluentdOutputBufferQueueLength
      expr: avg_over_time(fluentd_status_buffer_queue_length[{{ $.Values.prometheus.rule.alerts.fluentd.outputBufferQueueLength.lookbackTime }}]) > {{ $.Values.prometheus.rule.alerts.fluentd.outputBufferQueueLength.threshold }}
      for: {{ $.Values.prometheus.rule.alerts.fluentd.outputBufferQueueLength.for }}
      labels:
        severity: "{{ $.Values.prometheus.rule.alerts.fluentd.outputBufferQueueLength.severity }}"
      annotations:
        summary: {{`"Fluentd output buffer queue length size is too big"`}}
        description: {{`"Output plugin {{ $labels.type }} on Pod {{ $labels.namespace }}/{{ $labels.pod }} has a buffer that cannot be flushed.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"`}}
    {{- end }}


    {{- if $.Values.prometheus.rule.alerts.fluentd.highErrorRatio.enabled }}
    - alert: FluentdHighErrorRatio
      expr: |
        (
          sum by (type, plugin_id)(rate(fluentd_output_status_num_errors{plugin_id!~"{{ $.Values.prometheus.rule.alerts.fluentd.excludePluginIdRegex }}"}[{{ $.Values.prometheus.rule.alerts.fluentd.highErrorRatio.rateTime }}]))
          /
          sum by (type, plugin_id)(rate(fluentd_output_status_emit_count{plugin_id!~"{{ $.Values.prometheus.rule.alerts.fluentd.excludePluginIdRegex }}"}[{{ $.Values.prometheus.rule.alerts.fluentd.highErrorRatio.rateTime }}]))
        ) > {{ $.Values.prometheus.rule.alerts.fluentd.highErrorRatio.threshold }}
        and
        sum by (type, plugin_id)(rate(fluentd_output_status_emit_count{plugin_id!~"{{ $.Values.prometheus.rule.alerts.fluentd.excludePluginIdRegex }}"}[{{ $.Values.prometheus.rule.alerts.fluentd.highErrorRatio.rateTime }}])) > 0
      for: {{ $.Values.prometheus.rule.alerts.fluentd.highErrorRatio.for }}
      labels:
        severity: "{{ $.Values.prometheus.rule.alerts.fluentd.highErrorRatio.severity }}"
      annotations:
        summary: {{`"Fluentd high error ratio detected"`}}
        description: {{`"Fluentd error ratio is {{ $value | humanizePercentage }} for plugin {{ $labels.plugin_id }}\n  LABELS: {{ $labels }}"`}}
    {{- end }}

    {{- if $.Values.prometheus.rule.alerts.fluentd.highRetryRatio.enabled }}
    - alert: FluentdHighRetryRatio
      expr: |
        (
          sum by (type, plugin_id)(rate(fluentd_output_status_retry_count{plugin_id!~"{{ $.Values.prometheus.rule.alerts.fluentd.excludePluginIdRegex }}"}[{{ $.Values.prometheus.rule.alerts.fluentd.highRetryRatio.rateTime }}]))
          /
          sum by (type, plugin_id)(rate(fluentd_output_status_emit_count{plugin_id!~"{{ $.Values.prometheus.rule.alerts.fluentd.excludePluginIdRegex }}"}[{{ $.Values.prometheus.rule.alerts.fluentd.highRetryRatio.rateTime }}]))
        ) > {{ $.Values.prometheus.rule.alerts.fluentd.highRetryRatio.threshold }}
        and
        sum by (type, plugin_id)(rate(fluentd_output_status_emit_count{plugin_id!~"{{ $.Values.prometheus.rule.alerts.fluentd.excludePluginIdRegex }}"}[{{ $.Values.prometheus.rule.alerts.fluentd.highRetryRatio.rateTime }}])) > 0
      for: {{ $.Values.prometheus.rule.alerts.fluentd.highRetryRatio.for }}
      labels:
        severity: "{{ $.Values.prometheus.rule.alerts.fluentd.highRetryRatio.severity }}"
      annotations:
        summary: {{`"Fluentd high retry ratio detected"`}}
        description: {{`"Fluentd retry ratio is {{ $value | humanizePercentage }} for plugin {{ $labels.plugin_id }}\n  LABELS: {{ $labels }}"`}}
    {{- end }}


    {{- if $.Values.prometheus.rule.alerts.fluentd.outputRetryErrors.enabled }}
    - alert: FluentdOutputRetryErrors
      expr: rate(fluentd_output_status_num_errors{plugin_id!~"{{ $.Values.prometheus.rule.alerts.fluentd.excludePluginIdRegex }}"}[{{ $.Values.prometheus.rule.alerts.fluentd.outputRetryErrors.rateTime }}]) > {{ $.Values.prometheus.rule.alerts.fluentd.outputRetryErrors.threshold }}
      for: {{ $.Values.prometheus.rule.alerts.fluentd.outputRetryErrors.for }}
      labels:
        severity: "{{ $.Values.prometheus.rule.alerts.fluentd.outputRetryErrors.severity }}"
      annotations:
        summary: {{`"Fluentd send data errors"`}}
        description: {{`"Fluentd has errors when trying to send data to output. PluginId: {{ $labels.plugin_id }}"`}}
    {{- end }}



    {{- with $.Values.prometheus.rule.additionalAlerts }}
    {{ . | nindent 4 }}
    {{- end }}
{{- end }}
